In [2]:
import torch
print(torch.__version__)

2.8.0+cpu


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available")
    

GPU not available


## Creating Tensor

In [8]:
# using empty
a = torch.empty(2,3) # it allocated memory but did not initialize it

In [9]:
# check type
type(a)

torch.Tensor

In [10]:
# using zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(2,3)

tensor([[0.4197, 0.6288, 0.9813],
        [0.8633, 0.0725, 0.0228]])

In [13]:
torch.rand(2,3)

tensor([[0.0159, 0.8396, 0.6500],
        [0.3082, 0.3862, 0.8535]])

In [19]:
# if we want reproducibly 
torch.manual_seed(101)
torch.rand(2,3)

tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])

In [24]:
# using tensor
torch.tensor([2.5, 0.1])


tensor([2.5000, 0.1000])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0, 10, 2))

#linspace
print("using linspace ->", torch.linspace(0, 10, 5))


using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
