In [47]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [48]:
df = pd.read_csv("./data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [49]:
df.shape

(569, 33)

In [50]:
df.drop(columns=["id", "Unnamed: 32"], inplace=True)

In [51]:
df


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [52]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [53]:
y_train

122    M
82     M
317    M
364    B
392    M
      ..
441    M
157    B
278    B
112    B
552    B
Name: diagnosis, Length: 455, dtype: object

In [54]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [55]:
X_train

array([[ 2.9276533 ,  0.18557623,  3.11470326, ...,  1.70021599,
         0.51894512, -0.23465357],
       [ 3.2084867 ,  1.26378998,  3.33729468, ...,  2.65132711,
        -0.88927699,  1.10235762],
       [ 1.18185395, -0.11888752,  1.1197802 , ...,  0.97497456,
        -0.14699613, -0.13361594],
       ...,
       [-0.15861885, -0.35467524, -0.24348722, ..., -0.95720999,
        -0.92176193, -1.16804882],
       [ 0.03535886,  0.05967017,  0.243274  , ...,  0.55857534,
        -0.81943437,  1.26808072],
       [-0.3960244 ,  2.2985089 , -0.4488593 , ..., -0.7554638 ,
        -0.80481615, -1.04990429]], shape=(455, 30))

In [56]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [57]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [58]:
type(y_train)

numpy.ndarray

In [59]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [60]:
X_train_tensor.shape

torch.Size([455, 30])

In [61]:
X_train_tensor.shape

torch.Size([455, 30])

## Defining the model

In [62]:
class MySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
        
    def forward(self, X):
        return torch.sigmoid(X @ self.weights + self.bias) 

    def loss_function(self, y_pred, y):
        # Clamp y_pred to avoid log(0) which is undefined
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
        

In [63]:
learning_rate = 0.1
epochs = 50

In [64]:
# create model
model = MySimpleNN(X_train_tensor)
model.weights.shape

torch.Size([30, 1])

In [65]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [66]:
for epoch in range(epochs):
    # forward pass
    y_pred = model.forward(X_train_tensor)
    # compute loss
    loss = model.loss_function(y_pred, y_train_tensor)
    # backward pass
    loss.backward()
    # update weights
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item()}")




Epoch 1/50, Loss: 3.741986675074011
Epoch 2/50, Loss: 3.6164183136423147
Epoch 3/50, Loss: 3.4872916430442302
Epoch 4/50, Loss: 3.3522655957548353
Epoch 5/50, Loss: 3.212560821235212
Epoch 6/50, Loss: 3.0661694769184784
Epoch 7/50, Loss: 2.917992249657135
Epoch 8/50, Loss: 2.7633780014985407
Epoch 9/50, Loss: 2.6046903488167827
Epoch 10/50, Loss: 2.445466766998929
Epoch 11/50, Loss: 2.284065293634981
Epoch 12/50, Loss: 2.1177192971084375
Epoch 13/50, Loss: 1.9563261572159667
Epoch 14/50, Loss: 1.8041509178035358
Epoch 15/50, Loss: 1.659874947954589
Epoch 16/50, Loss: 1.5276739454048585
Epoch 17/50, Loss: 1.406904597265827
Epoch 18/50, Loss: 1.298183542027927
Epoch 19/50, Loss: 1.2023993453520967
Epoch 20/50, Loss: 1.1191622524442963
Epoch 21/50, Loss: 1.050400569554028
Epoch 22/50, Loss: 0.9946578934583925
Epoch 23/50, Loss: 0.9501346789201561
Epoch 24/50, Loss: 0.9148831819950332
Epoch 25/50, Loss: 0.8869710364125766
Epoch 26/50, Loss: 0.86463014509758
Epoch 27/50, Loss: 0.84637524407

In [67]:
model.weights

tensor([[-0.4489],
        [ 0.0329],
        [ 0.3900],
        [ 0.0912],
        [-0.1483],
        [ 0.1371],
        [ 0.2588],
        [ 0.1677],
        [ 0.2706],
        [-0.0216],
        [ 0.1419],
        [ 0.1395],
        [-0.2225],
        [ 0.1112],
        [-0.2104],
        [-0.4156],
        [-0.0352],
        [ 0.3242],
        [ 0.1964],
        [-0.0554],
        [-0.3162],
        [ 0.0605],
        [-0.1787],
        [ 0.2105],
        [ 0.0413],
        [ 0.3622],
        [-0.3394],
        [-0.2797],
        [-0.1278],
        [-0.1193]], dtype=torch.float64, requires_grad=True)

**Evaluation**

In [68]:
with torch.no_grad():
    y_pred_test = model.forward(X_test_tensor)
    y_pred_test = (y_pred_test >= 0.5).float()
    accuracy = (y_pred_test == y_test_tensor).float().mean()
print(f"Test Accuracy: {accuracy.item() * 100:.2f}%")    
y_pred_test

Test Accuracy: 59.05%


tensor([[1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      