In [2]:
import torch
print(torch.__version__)

2.8.0+cpu


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available")
    

GPU not available


## Creating Tensor

In [4]:
# using empty
a = torch.empty(2,3) # it allocated memory but did not initialize it

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.6355, 0.9726, 0.4865],
        [0.6945, 0.7411, 0.1040]])

In [9]:
torch.rand(2,3)

tensor([[0.2343, 0.7740, 0.5844],
        [0.9788, 0.3144, 0.8882]])

In [10]:
# if we want reproducibly 
torch.manual_seed(101)
torch.rand(2,3)

tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])

In [11]:
# using tensor
torch.tensor([2.5, 0.1])


tensor([2.5000, 0.1000])

In [12]:
# other ways

# arange
print("using arange ->", torch.arange(0, 10, 2))

#linspace
print("using linspace ->", torch.linspace(0, 10, 5))


using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [13]:
scaler = torch.tensor(8)
scaler, scaler.ndim, scaler.shape, scaler.shape

(tensor(8), 0, torch.Size([]), torch.Size([]))

In [14]:
matrix = torch.tensor([2, 4])
matrix


tensor([2, 4])

In [15]:
tensor = torch.tensor([[1,2,3],
                          [4,5,6],
                          [7,8,9]])

In [16]:
tensor, tensor.shape, tensor.ndim

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]),
 2)

In [17]:
rnadom_tensor = torch.rand(3,4)


In [18]:
rnadom_tensor, rnadom_tensor.shape, rnadom_tensor.ndim

(tensor([[0.9095, 0.3406, 0.4309, 0.7324],
         [0.4776, 0.0716, 0.5834, 0.7521],
         [0.7649, 0.1443, 0.7152, 0.3953]]),
 torch.Size([3, 4]),
 2)

In [19]:
tensor = torch.tensor([[[3,4,5,6,7,8]]])

In [20]:
tensor.ndim, tensor.shape, tensor

(3, torch.Size([1, 1, 6]), tensor([[[3, 4, 5, 6, 7, 8]]]))

In [21]:
tensor2 = torch.rand(1,3,4)
tensor2

tensor([[[0.6244, 0.3684, 0.8823, 0.3746],
         [0.1458, 0.3671, 0.5645, 0.5272],
         [0.1141, 0.0992, 0.1637, 0.7688]]])

In [22]:
torch3 = torch.rand(1,2,1,3,4)
torch3, torch3.ndim

(tensor([[[[[0.4825, 0.8019, 0.3917, 0.3275],
            [0.5084, 0.3454, 0.6221, 0.5695],
            [0.7171, 0.2488, 0.4384, 0.8215]]],
 
 
          [[[0.5741, 0.7075, 0.4120, 0.8646],
            [0.2945, 0.6296, 0.8637, 0.4373],
            [0.5454, 0.2737, 0.2903, 0.3664]]]]]),
 5)

**torch.full**

In [23]:
full_tensor = torch.full((5,3),10., dtype=int)
full_tensor

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

**6. Tensor datatypes**

In [24]:
full_tensor.dtype

torch.int64

In [25]:
x = torch.arange(1, 10)
x, x.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [26]:
x = x.type(torch.float64)
x, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64),
 torch.float64)

In [27]:
x.device

device(type='cpu')

**opretaion on tensors**

In [28]:
y = x+ 10

In [29]:
y+x

tensor([12., 14., 16., 18., 20., 22., 24., 26., 28.], dtype=torch.float64)

In [30]:
y-x

tensor([10., 10., 10., 10., 10., 10., 10., 10., 10.], dtype=torch.float64)

In [31]:
y*x

tensor([ 11.,  24.,  39.,  56.,  75.,  96., 119., 144., 171.],
       dtype=torch.float64)

In [32]:
matrixA = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
matrixB = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
matrixA, matrixB , matrixA.shape, matrixB.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]),
 torch.Size([3, 3]))

In [33]:
matrixA * matrixB

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [34]:
torch.matmul(matrixA, matrixB)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [35]:
matrixA @ matrixB

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [49]:
matrixB.shape

torch.Size([3, 3])

In [48]:
matrixB.transpose(0,1)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [40]:
matrixB

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

**reshaping, stacking, sqeezing, unsqeeze, permute**

In [51]:
matrixB.reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [62]:

matrixA, matrixB, matrixA.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [60]:
torch.stack([matrixA, matrixB], dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [77]:
x = torch.zeros(2,3,4)
x.ndim, x, x.shape

(3,
 tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.Size([2, 3, 4]))

In [69]:
y = torch.ones(2,3,4)

In [80]:
new_x = torch.stack([x,y],dim=0)
new_x, new_x.shape, new_x.ndim

(tensor([[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],
 
          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]],
 
 
         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]]]),
 torch.Size([2, 2, 3, 4]),
 4)

In [84]:
new_x = torch.stack([x,y],dim=1)
new_x, new_x.shape, new_x.ndim

(tensor([[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],
 
 
         [[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]]]),
 torch.Size([2, 2, 3, 4]),
 4)

In [82]:
new_x = torch.stack([x,y],dim=2)
new_x, new_x.shape, new_x.ndim

(tensor([[[[0., 0., 0., 0.],
           [1., 1., 1., 1.]],
 
          [[0., 0., 0., 0.],
           [1., 1., 1., 1.]],
 
          [[0., 0., 0., 0.],
           [1., 1., 1., 1.]]],
 
 
         [[[0., 0., 0., 0.],
           [1., 1., 1., 1.]],
 
          [[0., 0., 0., 0.],
           [1., 1., 1., 1.]],
 
          [[0., 0., 0., 0.],
           [1., 1., 1., 1.]]]]),
 torch.Size([2, 3, 2, 4]),
 4)